language: generic

os: osx
osx_image: xcode9.2

env:
  global:
    - COLUMNS=240
    - PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/jpeg-turbo/lib/pkgconfig:$PKG_CONFIG_PATH
    - HOMEBREW_NO_AUTO_UPDATE=1
    - HOMEBREW_NO_INSTALL_CLEANUP=1

before_install:
  - brew cleanup
  # Remove pre-installed Travis packages
  # See: https://github.com/travis-ci/packer-templates-mac/blob/master/playbooks/roles/homebrew/defaults/main.yml
  - brew uninstall boost carthage cgal dirmngr freexl gdal geos gnupg go icu4c jpeg json-c libgeotiff liblwgeom libspatialite libtiff maven md5deep mercurial msgpack node postgis postgresql pyenv python sfcgal sqlite swiftlint xctool
  - brew update
  - brew upgrade

install:
  - brew install advancecomp
  - brew tap kleisauke/libvips
  - brew install vips8 --build-bottle -v

script:
  - ./build/osx.sh

before_cache:
  - brew cleanup

cache:
  directories:
    # Cache downloaded bottles
    - $HOME/Library/Caches/Homebrew

addons:
  artifacts:
    s3_region: eu-west-1
