language: generic

os: osx
osx_image: xcode9.2

env:
  global:
    - COLUMNS=240

branches:
  only:
    - master

before_install:
  - brew cleanup
  - brew uninstall boost carthage cgal dirmngr freexl gdal go libgeotiff liblwgeom libspatialite libtiff maven mercurial postgis postgresql python sfcgal swiftlint
  - brew update
  - brew upgrade
  - brew cleanup

install:
  - brew install advancecomp
  - brew tap kleisauke/package-libvips-darwin https://github.com/kleisauke/package-libvips-darwin.git
  - brew install kleisauke/package-libvips-darwin/libtiff --build-bottle
  - brew install kleisauke/package-libvips-darwin/gdk-pixbuf --build-bottle
  - brew postinstall kleisauke/package-libvips-darwin/gdk-pixbuf
  - brew install kleisauke/package-libvips-darwin/vips --build-bottle

script:
  - export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/jpeg-turbo/lib/pkgconfig"
  - ./build/osx.sh

addons:
  artifacts:
    s3_region: eu-west-1
