language: generic

os: osx
osx_image: xcode9.2

env:
  global:
    - COLUMNS=240
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libffi/lib/pkgconfig

branches:
  only:
    - master

before_install:
  - brew cleanup
  - brew uninstall boost carthage cgal dirmngr freexl gdal go libgeotiff liblwgeom libspatialite maven mercurial postgis postgresql python sfcgal swiftlint
  - brew update
  - brew upgrade
  - brew cleanup

install:
  - brew install advancecomp
  - brew tap lovell/package-libvips-darwin https://github.com/lovell/package-libvips-darwin.git
  - brew install lovell/package-libvips-darwin/gdk-pixbuf --build-bottle
  - brew install lovell/package-libvips-darwin/vips --build-bottle

script:
  - ./build/osx.sh

addons:
  artifacts:
    s3_region: eu-west-1
